version: '3.2'
services:
  master:
    image: pwn3master
    build:
        context: .
        dockerfile: Dockerfile.master
    hostname: master.pwn3
    networks:
      default:
        aliases:
          - "master.pwn3"
    ports:
      - "3333:3333"
    volumes:
      - type: bind
        source: "./setup"
        target: "/opt/pwn3/setup"
      - type: bind
        source: "./server"
        target: "/opt/pwn3/server"
      - type: bind
        source: "./client"
        target: "/opt/pwn3/client"
      - type: volume
        source: data
        target: "/var/lib/postgresql"   
      - type: volume
        source: logs
        target: "/var/log/postgresql"
      - type: volume
        source: config 
        target: "/etc/postgresql"
    command: "/opt/pwn3/setup/masterServer.sh"
  game:
    image: pwn3game
    build:
        context: .
        dockerfile: Dockerfile.game
    hostname: game.pwn3
    networks:
      default:
        aliases:
          - "master.pwn3"
    ports:
      - "3000-3010:3000-3010"
    volumes:
      - type: bind
        source: "./client"
        target: "/opt/pwn3/client"
    depends_on:
      - master
# Persist PwnAdventure3 data beyond container lifetime 
volumes:
    data: {} 
    logs: {}
    config: {}
