FROM ubuntu:14.04

ENV PWN3=/opt/pwn3

RUN useradd -ms /bin/bash pwn3

# Binary must be run from this directory
WORKDIR $PWN3/client/PwnAdventure3_Data/PwnAdventure3/PwnAdventure3/Binaries/Linux
CMD ["./PwnAdventure3Server"]
